### PR TITLE
Added support for SKR Pro V1.1

### PR DESCRIPTION
**Pull request by SkullKill**
### Requirements

SKR Pro V1.1 board
optional, an I2C EEPROM module, e.g AT24C256

### Description

added support for SKR Pro V1.1

rename SKR13_2209 and SKR13_UART to SKR_2209 and SKR_UART to imply that they can be used for both SKR V1.3 and SKR Pro V1.1 boards

tested with the I2C EEPROM module (AT24C256), and UBL enabled

### Benefits

support for SKR Pro V1.1

### Related Issues

p.s the build in SD card on the SKR PRO v1.1 board does not work for printing. 
test print was done via octoprint.

----------------

CR-10S PRO - SKR Pro V1 1 - Breakout board - 01
there were a few issues with this mount, will post this once it is finalized.

CR-10S PRO - SKR Pro V1 1 - Breakout board - 02
E stepper motor cable was the wrong way in this pic

CR-10S PRO - SKR Pro V1 1 - Breakout board - 03
still testing, hence why the cable mess. will clean up and crimp some proper cables soon.

### CODE REVIEW

**Comment by InsanityAutomation** [comment]
BTW I rebased this locally and it currently fails on a couple libraries (neopixel and the current tmc library). Neopixel I can just kill since we dont need it. Im looking into which TMC Lib works with head currently then ill update this PR with a rebased copy to test. If we can confirm after rebasing it still works as intended ill get it merged shortly.

**Comment by InsanityAutomation** [comment]
Problem was a stale library in my build environment that wasnt needed for the platform... My bad! Builds ok now! Ill review it all one more time to make sure the rebase didnt mess anything up later on tonight and then get it merged in.

**Comment by InsanityAutomation** [comment]
Ok @SkullKill i think im good with how it looks now, if you dont have any issues with how it sits now, ill merge it tonight.

**Comment by SkullKill** [comment]
Had to increase the current for z to around 800++ ( need to double check the actual value). Was missing steps, and getting layer shift.

esteps for the extruder had to be increased to 650++ . Apparently enabling SQUARE_WAVE_STEPPING makes it better. Down to the 400 range . But I have not checked those yet.

I am not at home at the moment, ( in Mauritius at the moment) . Will be back end of Dec. Will check it then . 

Thanks for all your work!

**Comment by InsanityAutomation** [comment]
I actually have hybrid off for e and square wave on in nearly all my branches when UART is on, so im not sure how I missed this one! Ill add it to this PR

**Comment by InsanityAutomation** [comment]
https://github.com/MarlinFirmware/Marlin/issues/14684#issuecomment-564272484

FYI hopefully things will be in a better state on this board in a week or 2.

**Comment by LinoBarreca** [comment]
@InsanityAutomation actually I made the onboard sd work on 29 nov. but more changes are required (now) to avoid others' work again and again on the same things when I will implement other features.
if you need something "just working" to print from the onboard SD go [here](https://github.com/LinoBarreca/Marlin/pull/7) and pull *up to* the commits of 29 nov. (I don't exactly remember which one, you might need to read the comments to find out) there might be some debugging messages left here and there which you can comment out (I will remove them once "done")
I strongly suggest you to wait, however, if you don't have the urge to use the onboard sd.

**Comment by InsanityAutomation** [comment]
@LinoBarreca Im in no hurry, id rather it be stable! Ive got one on the bench to play with when time allows, but im in my day jobs busy season (automotive / industrial automation and christmas shutdown...) so until im through that itll be little more than poking :)

Between that and the servo stuff from the other thread as well as eeprom seems the few of you chasing it are having fun!

**Comment by jgwinner** [comment]
I've got a burned out CR-10 board, and a SKR Pro sitting here, dying to be swapped in. TMC2209's, dual Z, dual extruder, BL Touch

If I can help, let me know! I'm a C++ dev, although I don't know the deep guts of Marlin. Yet. 

        == John ==

**Comment by LinoBarreca** [comment]
@jgwinner do you know how to use git, right? If yes and you want to help you can contribute to the development here:
https://github.com/LinoBarreca/Marlin/pull/7
Take one task, checkout multispi, modify make pr.

**Comment by jgwinner** [comment]
Ok, I just downloaded SkullKill's branch, you want me to use the above? Will do.

It'll also mean I'll be merging in some of my CR-10 config changes I guess. I like to fiddle with config.h :)

**Comment by jgwinner** [comment]
Ok, I haven't done git downloading of pull requests from forks :) but I figured it out.

git clone https://github.com/LinoBarreca/Marlin -b MultiSPI

Working on it ... (fixed URL)

**Comment by LinoBarreca** [comment]
Custom configs are never merged. They must remain as local changes. Only source code gets merged. Also, use the link I provided to write with the others helping.
Collaborative development 💪

**Comment by jgwinner** [comment]
Understood. I think it's weird a "never merged" file actually is checked in, but I guess someone figured a default file was better than no file.

So, I have it working! 

A few notes, not sure if this is me or Marlin 2.0.

1) My BLTouch is very confused. I had it all dialed in, then it started printing in air. I rechecked everything, then it tried to push PAST THE MECHANICAL STOPS. I've had this problem before. I really think if a mechanical endstop is still hooked up, and the touch probe says 'no touch' the carriage should halt at the limit. Anyway, this is not specific to this branch. I may open a bug over at Marlin (again, a lot of it is my understanding, so I hold off until I exaust stuff).

2) Bigger issues/questions: With the onboard SDCard, I wasn't able to "Save to EEProm". I swapped out displays for a RepRapp, with a second SDCard, and I *think* it's saving (which I think caused an issue with 1), but it's not clear. I hvaen't pulled out the card to sector edit though. Will check that in a bit.  

A bit rambling for a quick note, but wanted to let you know I'm up. Is there any specific things I can do, to debug the SDCard access? I can swap out either display (with or without SDCard). 

        == John ==

**Comment by jgwinner** [comment]
Ok, so neither SD card is getting written to (or at least, nnot in the FAT32 section, I didn't pull partition tables and check that).

In PINS_BTT_SKR_PRO_V1_1.h there's a block:

```
#if HAS_SPI_LCD

  //
  // LCD Display output pins
  //
  #if ENABLED(REPRAPWORLD_GRAPHICAL_LCD)

    #define LCD_PINS_RS         49   // CS chip select /SS chip slave select
    #define LCD_PINS_ENABLE     51   // SID (MOSI)
    #define LCD_PINS_D4         52   // SCK (CLK) clock

  #elif BOTH(NEWPANEL, PANEL_ONE)

... etc. 

  #else

    #if ENABLED(CR10_STOCKDISPLAY)
```

but from what I can see, `#if HAS_SPI_LCD` is never set unless you have an "Ultra LCD" and that seems to be only some esoteric boards.

Does that explain why my EEPROM emulation doesn't work with either SD card, meaning, either the built in SD card with CR-10 display, OR the RepRap LCD display with SD Card #2?

        == John ==

**Comment by SkullKill** [comment]
@InsanityAutomation , tested from the CrealityDwin_2.0 branch.

all working except that i am getting "????" on top of the LCD. test print worked fine on the SKR Pro v1.1 .

esteps after calibration is very close to 140 now. (E138.96)

i am using 
Marlin/Configuration_adv.h

    #define Y_CURRENT     740  // instead of 720, will go back to 800 if there are missed steps. 

    #define Z_CURRENT       720  // instead of 850. i assume the reason you change that was because  other machines needs 850?? 720 is more than enough on the CR-10S Pro. (at least in my setup)

    #define STEALTHCHOP_E  // testing with stealthchop on extruder as well, so far it is working (need to monitor more closely if there are any missed steps). 


IMG_20200101_082351

IMG_20200101_082406

**Comment by SkullKill** [comment]
@LinoBarreca FYI, i just tested "M997" command and it works. It reboots the SKR Pro V1.1 board. (in relation to the discussion we had on facebook about updating the firmware via octoprint). just need to find a way to do CRC after the firmware has been transferred to the sd card?

**Comment by InsanityAutomation** [comment]
Did you update the screen files with DW5? I changed the header address to avoid data overlapping from another field when a filename was long enough. Ill add the updated current values to the devel branch after I finish adding the dual z stuff!

**Comment by SkullKill** [comment]
> Did you update the screen files with DW5?

that is it, i though i did check if there were new ones, but i was looking at the wrong one (CR-X_Stock_ScreenRev1.7z updated 4 month ago).

did not see "CR10SPro_Max_Ender5Plus_V2_Screen.7z" within the list of hex files. my bad :)

Happy new year by the way!

**Comment by SkullKill** [comment]
@InsanityAutomation  fancy new dark theme for the screens :)

MVIMG_20200101_124216

MVIMG_20200101_124221

**Pull request merged**
