### PR TITLE
Add support for the Trex 3 that was upgraded from the 2+ from the kit.

### PR DESCRIPTION
**Pull request by jim-edwards**
### Requirements

* Filling out this template is required. Pull Requests without a clear description may be closed at the maintainers' discretion.

### Description

Add support for a Formbot 3 that was upgraded from a 2+ via the official kit.  The kit included the same electronics, board, etc from the full 3 model, but has some slight differences in homing positions and offsets from the 2+ base hardware.

I am working on the configuration and have run basics tests, but am not confident the changes are complete yet.  Further review and testing is required, but I wanted to get some feedback.

### Benefits

Adds easy configuration for the kit, so users can just set a single option and properly configure the settings.

### CODE REVIEW

**Comment by jim-edwards** [comment]
Other things I might need to consider for this request:
   1)  Create a config in the config directory for upstream?
   2)  I wasn't sure if X2_MAX_POS in Configuration_adv.h needed updated yet.
   3)  Further review and testing.

Testing completed so far:
    * Basic movement all motors: Yes
    * Homing works: Yes
    * Move all motors to extremes: Yes
    * LED Control: Yes
    * Heating control and temp reading: Yes
    * Single Extruder Left Printing: Yes
    * Single Extruder Right Printing: No
    * IDEX Printing: No
    * Duplicate Printing: No
    * Mirror Printing: No

**Comment by jim-edwards** [comment]
The X axis is really close to the left edge of the bed when moved to X=0, but when moving the X axis to the max, X=400, it comes right up against the right extruder, so I think its correct, but not 100% sure if the left edge could be adjusted without impacting the right side.

**Comment by InsanityAutomation** [comment]
FYI, there is a known issue with positive hotend offsets applying when switching to T2. Im also working to add sanity checks and max offset clamping upstream along with the fix for that.

The original limit of 80 doesnt appear necessary on any machine honestly. IIRC it was copied from the original formbot stock firmware.

**Comment by InsanityAutomation** [comment]
FYI, included these changes in my last update since I didnt have permission to push any changes back to your branch.

**Comment by jim-edwards** [comment]
Thanks for including, I'll see if I can figure out the permissions in the future.  Just FYI, there appears to be 1 spot where the renamed variable was missed.  In Configuration.h, where it checks it the TREX3_UPGRADE is enabled, force setting TREX3, variable was not renamed there.

**Comment by InsanityAutomation** [comment]
Aye so there was! Fixed it now :)

**Comment by jim-edwards** [comment]
One more error in the script conversion:
#define Z_MIN_POS 3, this should be 0 for the non T-Rex 3, including the upgraded option.  Looks like its set to 3 in your most recent change, and it should be -3 on the normal T-Rex 3 (which looks correct).

**Pull request closed without merging**
